apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: postgres
  labels:
    service: postgres
spec:
  replicas: 1
  template:
    metadata:
      labels:
        service: postgres
    spec:
      volumes:
        - name: macedonieje-postgres-pvc
          persistentVolumeClaim:
            claimName: macedonieje-postgres-pvc
      containers:
        - name: postgres
          image: postgres:12.1
          imagePullPolicy: Always
          ports:
            - containerPort: 5432
          volumeMounts:
            - mountPath: /var/lib/postgres
              name: macedonieje-postgres-pvc
          resources:
            limits:
              cpu: 500m
              memory: 512Mi
            requests:
              cpu: 40m
              memory: 20Mi
          env:
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: password
