apiVersion : apps/v1beta1
kind: Deployment
metadata:
  name: klant-service
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: klant-service
    spec:
      containers:
        - name: klant-service
          image: minor2019.azurecr.io/macedonieje-klant-service
          imagePullPolicy: Always
          ports:
            - containerPort: 80
          resources:
            limits:
              cpu: 250m
              memory: 512Mi
            requests:
              cpu: 50m
              memory: 50Mi
          env:
            - name: BROKER_CONNECTION_STRING
              valueFrom:
                secretKeyRef:
                  name: rabbitmq-secret-url
                  key: url
            - name: BROKER_EXCHANGE_NAME
              valueFrom:
                secretKeyRef:
                  name: rabbitmq-secret-url
                  key: exchange
            - name: DB_CONNECTION_STRING
              valueFrom:
                secretKeyRef:
                  name: klantservice-secret
                  key: connectionString
