apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: pgadmin
  labels:
    service: pgadmin
spec:
  replicas: 1
  template:
    metadata:
      labels:
        service: pgadmin
    spec:
      containers:
        - name: pgadmin
          image: dpage/pgadmin4:4.16
          imagePullPolicy: Always
          ports:
            - containerPort: 5050
          resources:
            limits:
              cpu: 500m
              memory: 512Mi
            requests:
              cpu: 40m
              memory: 20Mi
          env:
            - name: PGADMIN_DEFAULT_EMAIL
              valueFrom:
                secretKeyRef:
                  name: pgadmin-secrets
                  key: email
            - name: PGADMIN_DEFAULT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: pgadmin-secrets
                  key: password
            - name: PGADMIN_LISTEN_PORT
              value: '5050'
