apiVersion: v1
kind: Service
metadata:
  name: rabbitmq-svc
  labels:
    service: rabbitmq-svc
spec:
  selector:
    service: rabbitmq
  ports:
    - name: bus  
      port: 5672
    - name: management  
      port: 15672

