apiVersion: v1
kind: Secret
metadata:
  name: rabbitmq-secret-url
data:
  url: YW1xcDovL3JhYmJpdG1xLWFkbWluOm5tY25qa2xoYWk3YTNramhramxsamVhaGZAcmFiYml0bXEtc3Zj
  exchange: S2FudGlsZXZlci5FdmVudGJ1cw==
